# General
name: Bryan Mayer
description: "Minimalistic, friendly, responsive."
url: http://bryanmayer.github.io

markdown: redcarpet
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
twitter: mayertbryan
www.github.com/bryanmayer: bryanmayer

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
