# General
name: Bryan T. Mayer
description: "Minimalistic, friendly, responsive."
url: http://bryanmayer.github.io

highlighter: rouge

paginate: 5
permalink: /:title

# Social share and comments.
twitter: mayertbryan
github: bryanmayer