# General
name: Minimal-Block
description: "Minimalistic, friendly, responsive."
url: http://bryanmayer.github.io

markdown: redcarpet
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
twitter: www.twitter.com/mayertbryan
github: www.github.com/bryanmayer

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
